apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: default
spec:
  encryptedData:
    token: AgArYEkl/oWtfOgV4tjzoZ/7bt+hZ4/hveCFBt/2at7nZC3Wo0nSTAfuBXgteki5FGcNwO+w3wlVlxJnft5HesYasAw3YjcCTZ9Z1tftYtRIVg4R0zeew79LSW6WSn4PWfYNfAl5puHAI576twTsZVBpI8O+HQ3vieleO9L/o1G/Q/sHsZY6ttNoqK2bT4AghG1hgP0CXySJWaI6GhkPa3dDGqQbdt9rGay0Pmhe2FYY1a7Cw3b6V8q6lATSnoeMJXHOlIztFfNYBf0xG32DMNjIM2qV06g9z2DQkMaG4/ZOjk+MMeLhhGr3PcDX2bxGCVDNZ0OifseS4aKBPA28MvcSBTdAYsXwxgUUfhvcwXwRYEyZNcGNsOBttUHxzzZj3tXlTP6TbJXR3cTZqJ6dJ/s65zYVSftljNPcxOyFGzupiQqITY4lcEdeN8c/0IwSpmCADyAQq9n23+fPjkQpdCFQyFpS2IfFOrPDRZzUefAbeTVu1SoNbHcFB8PslNly9a1Mxi902QhSnccUHl/sbGBY9mtNtkIG22LjJyaHIeF51wpC1S7sSGVCaEfD4dMg3LOH0CPRN60NqQoEQQZis3EJGzCm/rNx/YmPLxmDMKv2pPb8fRVHsSCq44Fi0nb1CIpLHqQnmOkozTFnasH8mWknhjrmwei5vQWZxXf95u3qQaJOzL6HDF74IOy1Payf91nOMHeo74sUeGmHxdRFb7noCfL9tZBaSgk=
