apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: guestbook
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: guestbook
